apiVersion: v2
appVersion: 1.0.1
description: A Helm chart for Kubernetes
home: https://github.com/clouddrove/helmchart
icon: https://raw.githubusercontent.com/clouddrove/helmchart/feat/github-action/images/helm.png
keywords:
- helm
- chart
- k8s
- helm-chart
maintainers:
- email: hello@clouddrove.com
  name: CloudDrove Inc
name: helmchart
type: application
version: 1.0.1
