name: smurf Helm Deployment
permissions:
  id-token: write
  contents: read
  pull-requests: write
on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      aws-region: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up smurf
      #   uses: clouddrove/smurf@master
      #   with:
      #     version: latest

      # - name: Setup Smurf
      #   uses: clouddrove/smurf@fix/selm-upgrade
      #   with:
      #     version: v0.1.4-Beta

      - name: Install Smurf manually
        run: |
          VERSION=v0.1.4-Beta
          curl -fL \
            https://github.com/clouddrove/smurf/releases/download/${VERSION}/smurf-linux-amd64 \
            -o smurf
          chmod +x smurf
          sudo mv smurf /usr/local/bin/smurf

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: "latest"

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      - name: Set up KIND cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: smurf-test

      - name: Add Helm repo and update
        run: |
            smurf selm repo add clouddrove https://charts.clouddrove.com/ 
            smurf selm repo clouddrove

      - name: Deploy helmchart
        id: deploy-to-eks
        env:
          AWS_REGION: us-west-2
          RELEASE_NAME: Clouddrove-nginx
          CHART: clouddrove/helmchart
          VALUES_FILE: "./values.yaml"
          NAMESPACE: dev

        run: |
          smurf selm upgrade --install ${{ env.RELEASE_NAME }} ${{ env.CHART }} \
          -f ${{ env.VALUES_FILE }} \
          --namespace ${{ env.NAMESPACE }} \
          --create-namespace \
          --atomic \
          --wait \
          --timeout 300 \
          --debug \

      - name: helm list 
        run: |
            helm history ${{ env.RELEASE_NAME }} -n dev 